EMOTION_LEXICON = {
    "joy": [
        "feliz", "felices", "alegre", "alegres", "alegría",
        "contento", "contenta", "contentos", "contentas",
        "orgulloso", "orgullosa", "orgullosos",
        "hermoso", "hermosa", "hermosos", "hermosas",
        "maravilloso", "maravillosa", "maravillosas", "maravillosos",
        "fantástico", "fantástica", "fantásticos", "fantásticas",
        "increíble", "increíbles",
        "excelente", "excelentes",
        "genial", "geniales",
        "bueno", "buena", "buenos", "buenas", "bonito", "bonita",
        "bonitos", "bonitas", "precioso", "preciosa",
        "encanta", "encantan", "encantó", "encantado", "encantadora",
        "gusta", "gustan", "gustó", "gustado", "gustaría",
        "divertido", "divertida", "gracioso", "graciosa",
        "bien", "mejor", "mejores", "perfecto", "perfecta", "perfectamente",
        "agradecido", "agradecida", "agradecidos", "gracias", "agradezco",
        "bendición", "bendiciones", "bendito", "bendita", "bendecido",
        "éxito", "exitosa", "exitoso", "exitosas", "exitosos",
        "triunfo", "victoria", "victorioso", "logro", "logros",
        "disfruta", "disfrutando", "disfruto", "celebrar", "celebrando",
        "apoyo", "apoyamos", "apoyar", "apoyan", "apoyó",
        "lindo", "linda", "lindos", "lindas",
        "felicidades", "felicitaciones", "felicito", "enhorabuena",
        "orgullo", "enorgullece",
        "cariño", "cariñoso", "cariñosa",
        "amor", "amable", "amables", "amabilidad",
        "sonrisa", "sonríe", "sonriente",
        "esperanza", "esperanzador", "esperanzadora",
        "ilusiona", "ilusionado", "ilusión",
        "motiva", "motivado", "motivación", "motivador",
        "animado", "animo", "ánimo",
        "festejar", "festejando", "fiesta",
        "agrada", "agradable", "agradables",
        "simpático", "simpática", "simpatía",
        "talentoso", "talentosa", "talento",
        "brillante", "brillantes",
        "destacado", "destacada", "destacan",
        "admirable", "admiro", "admiración",
        "magnífico", "magnífica",
        "estupendo", "estupenda",
        "espléndido", "espléndida",
        "extraordinario", "extraordinaria",
        "fenomenal", "fenomenales",
        "estuvo bueno",
    ],
    "anger": [
        "enoja", "enojo", "enojado", "enojada", "enojan", "enojosos",
        "rabia", "furioso", "furiosa", "furia", "furor",
        "indignado", "indignada", "indignación", "indigna", "indignante",
        "corrupto", "corrupta", "corruptos", "corrupción", "corruptelas",
        "ladrón", "ladrona", "ladrones", "robo", "robos", "roban", "robó",
        "robado", "robaron", "asaltantes", "asaltos",
        "mentira", "mentiras", "miente", "mienten", "engaño", "engañar",
        "engaña", "engañaron", "mentiroso", "mentirosa",
        "fracaso", "fracasados", "fracasó", "fracasar",
        "injusticia", "injusto", "injusta", "injustamente",
        "abuso", "abusos", "abusivo", "abusiva", "abusan", "abusó",
        "pésimo", "pésima", "pésimos", "pésimas",
        "horrible", "horribles", "terrible", "terribles",
        "basura", "desastre", "vergüenza", "vergonzoso", "vergonzosa",
        "odio", "odian", "odiado", "odiosa", "odioso",
        "incompetente", "incompetentes", "inepto", "inepta",
        "delincuente", "delincuencia", "delincuentes",
        "asqueroso", "asquerosa", "repugnante",
        "malo", "mala", "malos", "malas", "malísimo",
        "peor", "peores", "pésimo", "pésima",
        "detesto", "detestable", "detestan",
        "imbécil", "estúpido", "estúpida", "idiota",
        "molesta", "molesto", "molestan", "molestia",
        "fastidia", "fastidio", "fastidioso",
        "irritante", "irrita", "irritado",
        "desgraciado", "desgraciada", "desgracia",
        "maltrato", "maltratan", "maltratado",
        "inaguantable", "insoportable", "intolerable",
        "descontento", "descontenta", "descontentos",
        "queja", "quejas", "quejarse", "quejando",
        "protesta", "protestas", "protestando",
        "exigimos", "exijo", "exigen", "exigencia",
        "harto", "harta", "hartos", "hartas", "hartazgo",
        "cansado", "cansada", "cansancio",
        "desespera", "desesperante", "desesperación",
        "aburren", "aburrido", "aburrida", "aburrimiento",
    ],
    "sadness": [
        "triste", "tristes", "tristeza", "entristece", "entristeció",
        "deprime", "deprimente", "depresión", "deprimido", "deprimida",
        "llorar", "llora", "lloran", "llorando", "lágrimas", "lloró",
        "decepcionado", "decepcionada", "decepción", "decepciona",
        "desilusionado", "desilusionada", "desilusión",
        "abandono", "abandonado", "abandonada", "abandonan",
        "soledad", "solitario", "solitario",
        "pobre", "pobres", "pobreza", "empobrecido",
        "desempleo", "desempleados", "desempleada", "sin trabajo",
        "enfermo", "enferma", "enfermedad", "enfermos", "enfermedades",
        "falta", "carencia", "necesidad", "necesidades", "necesitamos",
        "perder", "perdió", "perdido", "pérdida", "perdemos",
        "lamento", "lamentable", "lamentablemente",
        "desesperanza", "desesperado", "desesperada",
        "sufrir", "sufre", "sufrimiento", "sufren", "sufrió",
        "dolor", "dolores", "doloroso", "duele", "duelen",
        "pena", "apenado", "apenada",
        "nostalgia", "nostálgico", "extraño", "extraña", "extrañar",
        "melancolía", "melancólico",
        "herido", "herida", "heridas",
        "preocupación", "preocupado", "preocupada", "preocupa",
        "angustia", "angustiado", "angustiada", "angustiante",
        "afligido", "afligida", "aflicción",
        "desconsuelo", "desconsolado",
        "desánimo", "desanimado", "desanimada",
        "impotencia", "impotente",
        "frustración", "frustrado", "frustrada", "frustra",
        "quebrantado", "quebrantada",
        "desolación", "desolado", "desolada",
    ],
    "fear": [
        "miedo", "temeroso", "temerosa", "temores", "temor", "temer",
        "inseguridad", "inseguro", "insegura",
        "peligro", "peligroso", "peligrosa", "peligrosos",
        "amenaza", "amenazas", "amenazado", "amenazante", "amenazan",
        "violencia", "violento", "violenta", "violentos",
        "asesinato", "asesinatos", "muerte", "muerto", "muerta",
        "muertos", "matar", "mataron", "matan", "mató",
        "extorsión", "extorsionan", "extorsionar", "extorsionistas",
        "pandilla", "pandilleros", "maras", "pandilleril",
        "preocupado", "preocupada", "preocupación", "preocupante",
        "riesgo", "riesgos", "arriesgado",
        "alerta", "emergencia", "pánico",
        "nunca", "jamás",
        "temblor", "terremoto", "desastre natural",
        "asustado", "asusta", "asustan", "asustó",
        "espanto", "espantoso", "espantosa",
        "aterrador", "aterradora", "aterrorizado",
        "horror", "horroroso", "horrorosa",
        "intranquilo", "intranquila", "intranquilidad",
        "desprotegido", "desprotegida", "desprotección",
        "vulnerable", "vulnerabilidad",
        "incertidumbre", "incierto", "incierta",
        "desconfianza", "desconfiado", "desconfiada",
        "alarma", "alarmante", "alarmado",
        "cuidado", "cuidadoso", "precaución",
        "temible", "temida", "temido",
    ],
    "disgust": [
        "asqueroso", "asquerosa", "repugnante", "repulsivo", "repulsiva",
        "repudio", "repudiable", "repudiar", "repudian",
        "detesto", "detestable", "detestan", "detesta",
        "asco", "nauseabundo", "nauseabunda",
        "podrido", "podrida", "putrefacto", "podredumbre",
        "sucio", "sucia", "suciedad", "sucios",
        "inmoral", "inmorales", "inmoralidad",
        "abyecto", "abyecta", "despreciable",
        "basura", "desechos", "desperdicios",
        "corrupto", "corrupta", "corrupción",
        "depravado", "depravada", "depravación",
        "degradante", "degradación", "degradado",
        "indecente", "indecencia",
        "obsceno", "obscena", "obscenidad",
        "vil", "vileza", "vilmente",
        "desprecio", "despreciable", "desprecian",
        "repulsa", "repulsivo", "repulsiva",
        "apestoso", "apestosa", "apestan",
        "asfixiante", "sofocante",
        "guarro", "guarra", "cochino", "cochina",
        "immundicia", "inmundo", "inmunda",
    ],
    "surprise": [
        "sorprende", "sorprendente", "sorprendió", "sorpresa", "sorprendido",
        "asombro", "asombroso", "asombrosa", "asombra", "asombrado",
        "impactante", "impactó", "impacta", "impactado",
        "impresionante", "impresionó", "impresiona", "impresionado",
        "increíble", "increíbles",
        "inesperado", "inesperada", "repentino", "repentina",
        "shock", "shocked", "pasmoso", "pasmo",
        "inopinado", "inopinada",
        "casualidad", "coincidencia", "imprevisto",
        "desconcertante", "desconcierta", "desconcertado",
        "alucinante", "alucina", "alucinado",
        "fascinante", "fascina", "fascinado",
        "milagro", "milagroso", "milagrosa",
        "impensado", "impensada", "impensable",
        "súbito", "súbita", "súbitamente",
        "abismal", "abismalmente",
        "drástico", "drástica", "drásticamente",
        "novedoso", "novedosa", "innovador",
        "revelador", "reveladora", "revelación",
        "notable", "notablemente",
    ],
}

EMOTION_COLORS = {
    "joy": "#00ff88",
    "anger": "#ff3355",
    "sadness": "#5599ff",
    "fear": "#ffb000",
    "disgust": "#8860ff",
    "surprise": "#00f0ff",
}
