GAZETTEER = {
    "colonias": [
        "colonia centroamericana", "colonia las magnolias",
        "colonia san miguelito", "colonia belen", "colonia belén",
        "colonia ferrocarril", "colonia san antonio",
        "colonia santa rosa", "colonia las flores",
        "colonia san jose", "colonia san josé",
        "colonia santa rosa de lima", "colonia los andes",
        "colonia altos del norte", "colonia santa elena",
        "colonia santa lucia", "colonia santa lucía",
        "colonia san miguel", "colonia la libertad",
        "colonia las delicias", "colonia el progreso",
        "colonia las palmeras", "colonia santa rita",
        "colonia buenos aires", "colonia san carlos",
        "colonia lourdes", "colonia san luis",
        "colonia los angeles", "colonia los ángeles",
        "colonia las brisas", "colonia el palomar",
        "colonia san rafael", "colonia san juan",
        "colonia san cristobal", "colonia san cristóbal",
        "colonia santa marta", "colonia la joya",
        "colonia san jeronimo", "colonia san jerónimo",
        "colonia la esperanza", "colonia el sauce",
        "colonia las mercedes", "colonia san vicente",
        "colonia santa fe", "colonia la paz",
        "colonia san luis mariscal", "colonia belen sur",
        "colonia belén sur", "colonia el progreso sur",
        "colonia las palmeras sur",
    ],
    "municipios": [
        "santa ana centro", "santa ana", "metapán", "metapan",
        "texistepeque", "candelaria", "coatepeque",
        "chalchuapa", "el congo", "san sebastian",
        "san sebastián", "santiago de la frontera",
        "masahuat", "santa rosa guachipilin",
    ],
    "funcionarios": [
        "jose chicas", "jose maria chicas", "jose maría chicas",
        "alcalde chicas", "chicas", "edil", "alcalde",
        "vicealcalde", "concejal", "concejala", "regidor",
        "sindico", "síndico", "director de obras",
        "encargado de despacho", "secretario municipal",
        "gustavo acevedo",
    ],
    "programas": [
        "paac", "plan de bacheo", "plan de asfalto",
        "plan invierno", "plan verano", "alumbrado publico",
        "alumbrado público", "mercado municipal",
        "cableado subterraneo", "cableado subterráneo",
        "ruta abriendo caminos", "santa ana centro verde",
        "plan de contingencia", "plan de recuperacion",
    ],
    "cantones": [
        "canton natividad", "canton el palmar", "canton primavera",
        "canton el porvenir", "canton las delicias", "canton san antonio",
        "canton santa rosa", "canton el carmen", "canton san jose",
        "canton san josé", "canton la esperanza", "canton los andes",
        "canton san rafael", "canton el progreso", "canton san luis",
        "canton las mercedes", "canton san juan", "canton santa rita",
        "canton san vicente", "canton santa elena",
    ],
    "caserios": [
        "caserio cruz verde", "caserio el tapias", "caserio san lucas",
        "caserio el papalon", "caserio el papalón",
        "caserio los castillos", "caserio las animas",
        "caserio las ánimas", "caserio el limo",
        "caserio san francisco", "caserio el rosario",
        "caserio san antonio", "caserio las flores",
        "caserio el centro", "caserio la union", "caserio la unión",
        "la panades", "lapanades",
    ],
    "lugares_emblematicos": [
        "parque libertad", "parque colon", "parque colón",
        "catedral de santa ana", "palacio municipal",
        "plaza mayor", "mercado central", "mercado municipal",
        "teatro de santa ana", "estadio olimpico",
        "estadio olímpico", "coliseo de santa ana",
        "bulevar los 44", "calle libertad",
        "avenida independencia", "terminal de buses",
        "terminal", "detras de la terminal", "detrás de la terminal",
        "el puente",
        "hospital san juan de dios",
        "lago de coatepeque", "los cobanos",
        "montañona", "la montañona", "cerro verde",
    ],
}

FUNCIONARIO_VARIANTS = {
    "jose chicas": ["jose chicas", "jose maría chicas", "alcalde chicas", "jose m chicas"],
    "alcalde": ["alcalde", "edil", "alcalde municipal", "sr alcalde", "sra alcaldesa"],
    "concejo": ["concejo", "concejales", "regidores", "cabildo"],
}
